version: '3.4'

services:

    data-ingest:
        build: .
        image: data-ingest
        container_name: data-ingest
        depends_on:
            - postgres
        networks:
            - network

    postgres:
        image: postgis/postgis
        environment:
            POSTGRES_PASSWORD: p
            PG_DATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - 5432:5432
        networks:
            - network

    pgadmin4:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: andrew@example.com
            PGADMIN_DEFAULT_PASSWORD: p
        volumes: 
            - pgadmin:/var/lib/pgadmin
        ports: 
            - 5000:80
        networks:
            - pgnetwork

networks:
    network:
        driver: bridge

volumes:
    postgres:
    pgadmin:
